Path shenangigans

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -16,28 +16,28 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  check-formatting:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check out github
-        uses: actions/checkout@v6
-        with:
-          submodules: recursive
+  # check-formatting:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check out github
+  #       uses: actions/checkout@v6
+  #       with:
+  #         submodules: recursive
 
-      - name: Set up Julia
-        uses: julia-actions/install-juliaup@v3
-        with:
-          channel: lts
+  #     - name: Set up Julia
+  #       uses: julia-actions/install-juliaup@v3
+  #       with:
+  #         channel: lts
 
-      - name: Install Formatters
-        run: |
-          sudo apt install -y clang-format black isort
-          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/posit-dev/air/releases/download/0.8.0/air-installer.sh | sh
-          julia --project=julia -e 'import Pkg; Pkg.add("JuliaFormatter")'
+  #     - name: Install Formatters
+  #       run: |
+  #         sudo apt install -y clang-format black isort
+  #         curl --proto '=https' --tlsv1.2 -LsSf https://github.com/posit-dev/air/releases/download/0.8.0/air-installer.sh | sh
+  #         julia --project=julia -e 'import Pkg; Pkg.add("JuliaFormatter")'
 
-      - name: Run formatting checks
-        run: |
-          make format-check || (echo "::error title=Formatting::Formatting check failed, run \`make format\` locally" && exit 1)
+  #     - name: Run formatting checks
+  #       run: |
+  #         make format-check || (echo "::error title=Formatting::Formatting check failed, run \`make format\` locally" && exit 1)
 
   build:
     runs-on: ${{matrix.os}}
@@ -72,6 +72,7 @@ jobs:
         run: |
           Add-Content $env:GITHUB_PATH "$(pwd)/stan/lib/stan_math/lib/tbb"
           Add-Content $env:GITHUB_PATH "$(pwd)/test_models/full"
+          Add-Content $env:GITHUB_PATH "C:/mingw64/bin"
 
       - name: Build C example (Windows)
         # if: runner.os == 'Windows'
@@ -222,6 +223,13 @@ jobs:
           julia --version
           julia --project=. -e "using Pkg; Pkg.instantiate()"
           julia --project=. -e "using BridgeStan"
+
+      - name: Set up PATH for C example
+        # if: runner.os == 'Windows'
+        run: |
+          Add-Content $env:GITHUB_PATH "$(pwd)/stan/lib/stan_math/lib/tbb"
+          Add-Content $env:GITHUB_PATH "C:/mingw64/bin"
+
 
       - name: Run example
         run: |
